const prompts = [
  {
  id: 2,
  name: "1/7 Scale Gamer Figurine",
  short: "Hyper-realistic collectible toy desk scene",
  description: "A commercialized 1/7 scale figurine of a character placed on a modern gaming desk setup. The scene includes a glossy premium toy box, realistic unboxing details, and a curved monitor showing the 3D modeling process. Designed in a hyper-realistic collectible toy style with clean molded details and natural reflections.",
  original: "assets/img/figurine_original.webp",
  ai: "assets/img/figurine_ai.webp",
  prompt: "Using nano-banana model, the commercialization of 1/7 of the characters in the drawing realistic style, real environment, handmade on the computer desk, the contents of the computer screen are the hand done C4D modeling process, the computer screen is placed next to the computer screen, the BANDAI style plastic toy box printed with the original painting, and the computer table also has handmade tools, such as brush, pigment, knife, etc.' Create a 1/7 scale commercialized figurine of the character based on the reference photo. The figurine must keep the exact outfit and pose: The figure should be designed in a hyper-realistic collectible toy style, made of glossy high-quality plastic with clean molded details, subtle shading, and a slight reflective sheen. It is posed naturally on a round transparent acrylic base (no text or logos on the base). The figurine is placed on a modern desk setup.surrounded by everyday desk items. A curved gaming monitor in the background shows a 3D modeling process of this same figurine, with visible wireframe and render preview elements. Next to the screen, there is a large toy packaging box labeled 'YOUR NAME', styled like a premium gamer collectible package. The box must be much larger than the toy, with a semi-open transparent front panel so the figurine is partially visible inside. The packaging design combinescharacter themes - along with flat 2D illustrations of the character. The box should look glossy, bold, and premium, like high-end merchandise On the desk, scatter realistic unboxing details: a folded user manual, a few loose plastic blister tray parts, accessory pieces (extra sunglasses, controller prop, alternate hand), packaging foam, and a small cutting tool or tape suggesting the toy was just unpacked. The entire scene should berendered in ultra-realistic photographic quality, with RGB ambient desk lighting, sharp depth-of-field focus, and natural reflections on the glossy toy surface, making it look like a real collectible gamer figurine display.",
  tags: ["figurine", "collectible", "toy", "desk setup", "realistic", "premium packaging"],
  model: "Gemini",
  resolution: "1920x1080",
  likes: 60,
  dislikes: 3,
  basePrompt: "figurine",
  owner: "VoltNexis"
  },
  {
  id: 3,
  name: "Cinematic Elite Portrait",
  short: "Stylish man on leather sofa in noir-inspired room",
  description: "A hyper-realistic cinematic portrait of a confident young man dressed in a sharp black suit, sunglasses, and wristwatch, seated on a luxurious dark brown leather Chesterfield sofa. The moody room features black walls, a glowing chandelier, and a gothic painting of a hooded skull behind him. The composition emphasizes elegance, mystery, and power with dramatic lighting.",
  original: "assets/img/portrait_original.webp",
  ai: "assets/img/portrait_ai.webp",
  prompt: "A hyper-realistic image of a confident, stylish young man (face should match the uploaded reference image) sitting on a luxurious dark brown leather chesterfield sofa in a dimly lit, opulent room. He is dressed sharply in a black suit with a white shirt slightly unbuttoned, wearing black leather shoes, a wristwatch, and dark sunglasses. His pose is relaxed, with one leg crossed and one arm casually resting on the armrest. The setting features a dark, moody background with rich black walls, a classic chandelier with warm glowing bulbs hanging above, and a gothic-style painting of a hooded skull figure behind him The atmosphere is intense, cinematic, and mysterious, with dramatic lighting emphasizing elegance, power, and control. Style: hyper-realistic, cinematic lighting, rich tones, dark aesthetic Face: match exactly with the uploaded image Aspect Ratio: 3:2 or 4:5 vertical Camera Angle: eye level, symmetrical frame Mood: powerful, elite, mysterious, noir-inspired",
  tags: ["portrait", "cinematic", "noir", "luxury", "hyper-realistic", "elite"],
  model: "Gemini",
  resolution: "1536x1024",
  likes: 5,
  dislikes: 0
},
{
  id: 9,
  name: "Elegant Saree Portrait",
  short: "Girl in elegant realistic saree",
  description: "A photorealistic portrait of a girl with her original face, skin tone, hairstyle, and expression kept unchanged. Her outfit is replaced with an elegant saree that drapes naturally over her body with realistic fabric folds, shadows, and highlights. The saree looks authentic in silk or chiffon texture, blending seamlessly with her posture. The background and environment remain untouched, with cinematic lighting enhancing realism.",
  original: "assets/img/saree_original.webp",
  ai: "assets/img/saree_ai.webp",
  prompt: "Replace the girl’s outfit with a realistic, elegant saree while keeping her face, skin tone, body shape, hairstyle, and expression unchanged. The saree should appear natural, well-fitted, with detailed textures (silk/cotton/chiffon), realistic folds, shadows, and highlights, draping properly over the body. Background and environment remain untouched. Ultra realistic, high detail, sharp focus, natural fabric texture, cinematic lighting.",
  tags: ["portrait", "saree", "fashion", "ultra realistic", "cinematic", "fabric texture"],
  model: "Gemini",
  resolution: "2048x1365",
  likes: 9,
  dislikes: 0
},
{
  id: 4,
  name: "Black & White Water Portrait",
  short: "Close-up of man’s wet face emerging from water",
  description: "A dramatic black and white close-up portrait showing only the right side of a man's face emerging from water. His wet skin and hair glisten with water droplets and small bubbles. Strong directional lighting highlights the illuminated side while the other fades into deep shadow. The cinematic composition emphasizes texture, sharp eye detail, and an intense mysterious atmosphere against a dark, minimal background.",
  original: "assets/img/water_face_original.webp",
  ai: "assets/img/water_face_ai.webp",
  prompt: "Generate a black and white close-up portrait showing only the right side of a man's face emerging from water. His skin and hair are wet, with visible water droplets and bubbles. Use dramatic lighting to illuminate one side, leaving the other in deep shadow. Emphasize sharp eye detail, skin texture, and cinematic intensity with a minimal dark background.",
  tags: ["portrait", "black and white", "cinematic", "dramatic lighting", "water", "intense"],
  model: "Gemini",
  resolution: "1080x1350",
  likes: 114,
  dislikes: 5
},
{
  id: 5,
  name: "Golden Cinematic Portrait",
  short: "Stylish South Asian man in golden dramatic light",
  description: "A cinematic ultra-realistic portrait of a young South Asian man wearing retro round sunglasses, a wavy dark brown shirt with teal and beige tones, a gold chain, and a modern black watch. He poses confidently with one fist raised near his chin, illuminated by dramatic golden side lighting. The background features textured golden particles fading into deep shadows, creating a moody fashion editorial atmosphere. Shot with an 85mm lens look, shallow depth of field, and professional studio lighting.",
  original: "assets/img/golden_portrait_original.webp",
  ai: "assets/img/golden_portrait_ai.webp",
  prompt: "A cinematic portrait of a young South Asian man sitting confidently in dramatic golden light. He wears retro-style round sunglasses, a wavy-patterned dark brown shirt with teal and beige tones, a gold chain, and a modern black watch. His pose is stylish and bold, with one fist gently raised near his chin. The background features warm, textured golden particles illuminated by a side light, blending into deep shadows. The lighting is soft but directional, with strong highlights and shadows on the face. Ultra-realistic, high-resolution, 85mm lens look, shallow depth of field, professional fashion editorial lighting.",
  tags: ["portrait", "cinematic", "golden light", "editorial", "fashion", "south asian", "ultra-realistic"],
  model: "Gemini",
  resolution: "2048x1365",
  likes: 132,
  dislikes: 4
},
{
  id: 6,
  name: "Double Exposure Cityscape",
  short: "Side profile with post-apocalyptic city silhouette",
  description: "A cinematic double-exposure digital artwork featuring a young man's side profile wearing sunglasses. His silhouette blends seamlessly with a dramatic post-apocalyptic cityscape, where the same man is seen walking through burning ruins, glowing embers, and destroyed streets. The fiery sunset casts golden highlights and deep shadows, creating a heroic and introspective atmosphere that emphasizes resilience and strength amidst chaos. Rendered in high detail with realistic textures and concept art style.",
  original: "assets/img/double_exposure_original.webp",
  ai: "assets/img/double_exposure_ai.webp",
  prompt: "Cinematic double exposure digital artwork featuring a young man's side profile wearing sunglasses, seamlessly blended with a dramatic post-apocalyptic cityscape inside his silhouette. The inner silhouette shows the same man walking through a destroyed urban street with burning buildings, ruins, glowing embers, and fire all around. The lighting is moody and warm, with a fiery sunset casting golden highlights and deep shadows. The mood is heroic and introspective, emphasizing resilience and strength amidst chaos. High detail, realistic textures, 8K resolution, concept art style.",
  tags: ["double exposure", "cinematic", "post-apocalyptic", "concept art", "cityscape", "heroic", "introspective"],
  model: "Gemini",
  resolution: "7680x4320",
  likes: 94,
  dislikes: 0
},
{
  id: 7,
  name: "Rainy Fashion Portrait",
  short: "Model in heavy rain with cinematic expression",
  description: "A dramatic editorial-style portrait of a stylish model standing in heavy rain, soaked and expressive. He wears a semi-wet white dress shirt with subtle transparency, artistically clinging to his form. The model looks upward with an emotional cinematic expression as raindrops are captured midair. The scene features dramatic cool blue-toned lighting, soft mist in the background, and a shallow depth of field for a moody high-fashion aesthetic.",
  original: "assets/img/rainy_portrait_original.webp",
  ai: "assets/img/rainy_portrait_ai.webp",
  prompt: "A stylish model standing in heavy rain, soaked and expressive, wearing a semi-wet white dress shirt with subtle transparency, artistically clinging to his form. He looks upward with a cinematic, emotional expression. Rain droplets suspended midair, dramatic lighting with cool blue tones, soft mist in the background, shallow depth of field. Editorial fashion shoot style, ultra-high resolution.",
  tags: ["portrait", "fashion", "rain", "cinematic", "editorial", "blue tones", "emotional"],
  model: "Gemini",
  resolution: "4096x2730",
  likes: 87,
  dislikes: 3
},
{
  id: 8,
  name: "Cyberpunk Neon Streets",
  short: "Hyper-realistic neon-lit cyberpunk city",
  description: "A hyper-realistic cyberpunk masterpiece featuring neon-lit streets reflecting on wet pavement, futuristic holograms floating around, and people with glowing tattoos. Rain falls in slow motion, with cinematic lighting in vibrant magenta and teal contrast. The scene is ultra-detailed, gritty, and atmospheric, evoking a Blade Runner–style futuristic city.",
  original: "assets/img/cyberpunk_original.webp",
  ai: "assets/img/cyberpunk_ai.webp",
  prompt: "Turn this photo into a hyper-realistic cyberpunk masterpiece — neon-lit streets reflecting on wet pavement, futuristic holograms floating around, glowing tattoos on people, rain falling in slow motion, cinematic lighting with vibrant magenta and teal contrast, ultra-detailed with a gritty Blade Runner atmosphere.",
  tags: ["cyberpunk", "neon", "futuristic", "Blade Runner", "cinematic", "rain", "ultra-detailed"],
  model: "Gemini",
  resolution: "3840x2160",
  likes: 34,
  dislikes: 0
},
{
  id: 10,
  name: "Vibrant Holi Festival",
  short: "Girl in traditional attire with Holi powders",
  description: "A realistic and vibrant transformation of a portrait into an Indian Holi festival scene. The subject’s face remains unchanged, but her attire is replaced with traditional Indian clothing. Bright Holi powders fill the air, illuminated by colorful festive lights in the background. The scene looks joyful, energetic, and cinematic, with rich colors, natural fabric textures, and realistic lighting.",
  original: "assets/img/holi_original.webp",
  ai: "assets/img/holi_ai.webp",
  prompt: "Convert this photo into an Indian festival scene. Add colorful Holi powders in the air, bright festive lights in the background, and traditional attire on the subject. Keep the face unchanged but enhance the atmosphere to look vibrant, joyful, and realistic. Ultra realistic, sharp focus, natural fabric texture, cinematic lighting, vibrant colors.",
  tags: ["festival", "Holi", "Indian attire", "vibrant", "traditional", "cinematic"],
  model: "Gemini",
  resolution: "2048x1365",
  likes: 298,
  dislikes: 5
},
{
  id: 11,
  name: "Futuristic Cyberpunk Portrait",
  short: "Neon tattoos, headset, holographic city backdrop",
  description: "A hyper-detailed cyberpunk portrait transformation. The subject’s face remains recognizable, but enhanced with glowing neon tattoos, a high-tech headset, and futuristic styling. The background features a holographic cityscape with neon-lit skyscrapers and glowing effects. The atmosphere is ultra-cinematic with vibrant magenta and teal lighting, capturing the signature cyberpunk aesthetic.",
  original: "assets/img/cyberpunk_portrait_original.webp",
  ai: "assets/img/cyberpunk_portrait_ai.webp",
  prompt: "Transform this portrait into a futuristic cyberpunk look. Add glowing neon tattoos, a high-tech headset, and a holographic city background. Keep the person’s face recognizable but enhance with cyberpunk aesthetics. Make it ultra detailed and cinematic with neon lighting.",
  tags: ["portrait", "cyberpunk", "futuristic", "neon", "holographic", "cinematic", "ultra detailed"],
  model: "Gemini",
  resolution: "3840x2160",
  likes: 47,
  dislikes: 2
},
{
  id: 12,
  name: "Pixar-Style 3D Cartoon Portrait",
  short: "Soft 3D cartoon style with cheerful background",
  description: "A Pixar-inspired 3D cartoon transformation of the portrait. The subject’s facial features and hairstyle remain recognizable but are rendered in a soft, detailed animation style. The background is kept simple with bright, cheerful colors, creating a playful and lively atmosphere while maintaining a high-quality, polished look.",
  original: "assets/img/pixar_cartoon_original.webp",
  ai: "assets/img/pixar_cartoon_ai.webp",
  prompt: "Turn this photo into a Pixar-style 3D cartoon version. Keep the facial features and hairstyle recognizable but render them in soft, detailed animation style. Background should remain simple with bright cheerful colors.",
  tags: ["portrait", "Pixar", "3D cartoon", "animation", "stylized", "cheerful", "soft detail"],
  model: "Gemini",
  resolution: "3840x2160",
  likes: 23,
  dislikes: 1
},
{
  "id": 13,
  "name": "Professional LinkedIn Headshot",
  "short": "Formal suit, clean background, business-ready",
  "description": "This prompt transforms a casual portrait into a professional LinkedIn-style headshot. The subject’s face, expression, and skin tone remain unchanged while the outfit is replaced with a sharp formal suit. The background is clean and minimal, with soft studio lighting that enhances professionalism. The result is sharp, realistic, and ideal for business or career profiles.",
  "original": "assets/img/linkedin_headshot_original.webp",
  "ai": "assets/img/linkedin_headshot_ai.webp",
  "prompt": "Transform this casual photo of a person into a professional headshot for LinkedIn. Keep the face, expression, and skin tone unchanged, but change the outfit into a formal suit. Use a clean background with soft lighting. Make the image look sharp, realistic, and business-ready.",
  "tags": ["portrait", "professional", "headshot", "business", "LinkedIn", "formal"],
  "model": "Gemini",
  "resolution": "2048x2048",
  "likes": 89,
  "dislikes": 4
},
{
  "id": 14,
  "name": "Giant iPhone Spotify Model Shot",
  "short": "Standing on iPhone 16 screen with Spotify playlist",
  "description": "A stylish portrait of a young male model standing on a giant iPhone 16 screen. The phone’s display shows Spotify playing The Weeknd’s song ‘Heartless’. The subject wears 2025 AirPods Max, an oversized white T-shirt, black shorts, and white Air Jordans. Captured from a dramatic top-down angle, the shot emphasizes the scale of the phone. The atmosphere is sleek, modern, and minimal, blending fashion photography with futuristic digital aesthetics.",
  "original": "assets/img/giant_iphone_original.webp",
  "ai": "assets/img/giant_iphone_ai.webp",
  "prompt": "A stylish photo of a young male model standing on a giant iPhone 16 screen showing Spotify playlist of The Weeknd's Heartless song. He wears 2025 AirPods Max, an oversized white T-shirt, black shorts, and white Air Jordans. The top-down angle highlights the scale of the phone. The vibe is sleek, modern, and minimal.",
  "tags": ["fashion", "modern", "minimal", "futuristic", "iPhone", "Spotify"],
  "model": "ChatGPT",
  "resolution": "3840x2160",
  "likes": 156,
  "dislikes": 7
},
{
  "id": 15,
  "name": "Tokyo Neon Night Portrait",
  "short": "Stylish model in Tokyo night scene",
  "description": "A cinematic portrait of a stylish young male model set against the iconic Tokyo night atmosphere. The background features colorful neon lights, large digital billboards, glowing Japanese shop signs, and wet streets reflecting the vibrant colors after rain. A few pedestrians in the distance add an authentic urban touch, while the focus remains on the subject. The image blends fashion photography with the cinematic vibrancy of Tokyo’s nightlife.",
  "original": "assets/img/tokyo_night_original.webp",
  "ai": "assets/img/tokyo_night_ai.webp",
  "prompt": "The background captures the iconic night atmosphere of Tokyo: colorful neon lights, large digital billboards, shops with Japanese signs, and wet streets reflecting the lights after rain. A few pedestrians walk in the distance, adding an urban vibe while keeping the focus on the main subject. Aspect ratio: 9:16.",
  "tags": ["fashion", "tokyo", "neon", "urban", "cinematic", "nightlife"],
  "model": "Gemini",
  "resolution": "2160x3840",
  "likes": 72,
  "dislikes": 3
},
{
  "id": 16,
  "name": "Urban Street Racer Portrait",
  "short": "Baggy streetwear, BMW E46 M3, neon-lit Asian city",
  "description": "A cinematic visualization of the subject as a confident young man wearing a drop-shoulder oversized T-shirt and baggy jeans, leaning casually against a highly customized BMW E46 M3. The car features a sleek, modern blue and silver street racing paint job. The setting is a bustling Asian city road (Dhaka or Bangkok) filled with motion-blurred pedestrians and neon-lit traffic, creating a dynamic and urban atmosphere. The mood is gritty, inspired by the Need for Speed game series, with moody lighting, wet street reflections, and a strong glow from neon signs. The subject’s original face, hairstyle, and skin tone remain unchanged.",
  "original": "assets/img/street_racer_original.webp",
  "ai": "assets/img/street_racer_ai.webp",
  "prompt": "Visualize this person as a confident young man wearing a drop-shoulder oversized T-shirt and baggy jeans, leaning casually against a highly customized BMW E46 M3 with a sleek modern blue and silver street racing paint job. The setting is a bustling Asian city road (Dhaka or Bangkok) filled with motion-blurred people and neon-lit traffic. The scene should have a cinematic, gritty, urban feel inspired by the Need for Speed game series. The lighting is moody with street reflections and a strong glow from nearby signs. KEEP the person’s original face, hairstyle, and skin tone exactly the same — no facial changes at all. Aspect ratio: 9:16.",
  "tags": ["streetwear", "BMW", "urban", "cinematic", "neon", "Need for Speed", "cityscape", "fashion"],
  "model": "ChatGPT",
  "resolution": "2160x3840",
  "likes": 201,
  "dislikes": 12
},
  {
    "id": 17,
    "name": "Shimmering Rift Explorer",
    "short": "Young explorer at the edge of two universes",
    "description": "A young explorer stands at the edge of a shimmering rift between two universes — one side lush and organic, the other digital and geometric — colors blend into fractal reflections, glowing dust floating mid-air, cinematic lighting, ultra-real sense of scale, dreamlike tension between nature and code.",
    "original": "assets/img/rift_explorer_original.webp",
    "ai": "assets/img/rift_explorer_ai.webp",
    "prompt": "A young explorer stands at the edge of a shimmering rift between two universes — one side lush and organic, the other digital and geometric — colors blend into fractal reflections, glowing dust floating mid-air, cinematic lighting, ultra-real sense of scale, dreamlike tension between nature and code.",
    "tags": ["explorer", "rift", "universe", "cinematic", "realistic", "dreamlike"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 38,
    "dislikes": 1
  },
  {
    "id": 18,
    "name": "Golden Ruins Explorer",
    "short": "Person standing among ancient ruins glowing under sunlight",
    "description": "Keep the face realistic, place the person standing among ancient ruins glowing under golden sunlight, light dust particles in air, realistic sandstone textures, soft warm tones, cinematic focus depth, emotionally calm and powerful.",
    "original": "assets/img/golden_ruins_original.webp",
    "ai": "assets/img/golden_ruins_ai.webp",
    "prompt": "Keep the face realistic, place the person standing among ancient ruins glowing under golden sunlight, light dust particles in air, realistic sandstone textures, soft warm tones, cinematic focus depth, emotionally calm and powerful.",
    "tags": ["explorer", "ruins", "cinematic", "realistic", "sunlight", "emotional"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 145,
    "dislikes": 8
  },
  {
    "id": 19,
    "name": "Aurora Explorer",
    "short": "Person under the aurora borealis in explorer outfit",
    "description": "The person wearing a warm explorer outfit under the aurora borealis, soft snowlight reflecting on the face, glowing ice fields, dramatic lighting from green and pink northern lights, ultra-real cinematic vibe.",
    "original": "assets/img/aurora_explorer_original.webp",
    "ai": "assets/img/aurora_explorer_ai.webp",
    "prompt": "The person wearing a warm explorer outfit under the aurora borealis, soft snowlight reflecting on the face, glowing ice fields, dramatic lighting from green and pink northern lights, ultra-real cinematic vibe.",
    "tags": ["explorer", "aurora", "cinematic", "realistic", "snow", "northern lights"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 67,
    "dislikes": 2
  },
  {
    "id": 20,
    "name": "Dreamscape Lake Portrait",
    "short": "Person sitting beside a glowing lake with surreal skies",
    "description": "The real person sitting beside a glowing lake reflecting surreal skies made of clouds and stars, mist rising from water, floating petals around, photorealistic lighting, ethereal and peaceful tone.",
    "original": "assets/img/dreamscape_lake_original.webp",
    "ai": "assets/img/dreamscape_lake_ai.webp",
    "prompt": "The real person sitting beside a glowing lake reflecting surreal skies made of clouds and stars, mist rising from water, floating petals around, photorealistic lighting, ethereal and peaceful tone.",
    "tags": ["portrait", "dreamscape", "lake", "realistic", "ethereal", "cinematic"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 93,
    "dislikes": 5
  },
  {
    "id": 21,
    "name": "Stealth City Portrait",
    "short": "Person as stealth figure under neon-lit city lights",
    "description": "The person as a realistic stealth figure under city lights, black coat, light rain, neon reflections, shallow depth of field, cinematic composition, focus on eyes and motion blur in background.",
    "original": "assets/img/stealth_city_original.webp",
    "ai": "assets/img/stealth_city_ai.webp",
    "prompt": "The person as a realistic stealth figure under city lights, black coat, light rain, neon reflections, shallow depth of field, cinematic composition, focus on eyes and motion blur in background.",
    "tags": ["portrait", "stealth", "city", "neon", "cinematic", "realistic"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 124,
    "dislikes": 6
  },
  {
    "id": 22,
    "name": "Renaissance Oil Portrait",
    "short": "Transform into Renaissance-style oil painting",
    "description": "Transform the photo into a realistic Renaissance-style oil painting, deep shadows, warm tones, fabric detail, painterly texture on background but face remains real and detailed, inspired by Rembrandt and Da Vinci.",
    "original": "assets/img/renaissance_original.webp",
    "ai": "assets/img/renaissance_ai.webp",
    "prompt": "Transform the photo into a realistic Renaissance-style oil painting, deep shadows, warm tones, fabric detail, painterly texture on background but face remains real and detailed, inspired by Rembrandt and Da Vinci.",
    "tags": ["portrait", "renaissance", "oil painting", "cinematic", "realistic", "artistic"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 81,
    "dislikes": 3
  },
  {
    "id": 23,
    "name": "Abandoned City Survivor",
    "short": "Person in abandoned city with overgrown plants",
    "description": "Keep person realistic, standing in an abandoned city with overgrown plants, dusty sunlight filtering through broken windows, cinematic realism, slightly desaturated tone, hopeful yet strong expression.",
    "original": "assets/img/abandoned_city_original.webp",
    "ai": "assets/img/abandoned_city_ai.webp",
    "prompt": "Keep person realistic, standing in an abandoned city with overgrown plants, dusty sunlight filtering through broken windows, cinematic realism, slightly desaturated tone, hopeful yet strong expression.",
    "tags": ["portrait", "abandoned", "city", "cinematic", "realistic", "hopeful"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 176,
    "dislikes": 9
  },
  {
    "id": 24,
    "name": "Mystical Forest Portrait",
    "short": "Person surrounded by glowing plants and fireflies",
    "description": "Realistic person surrounded by glowing plants and soft fireflies, fog rays cutting through tall trees, green and gold lighting balance, magical realism tone, natural but fantastical.",
    "original": "assets/img/mystical_forest_original.webp",
    "ai": "assets/img/mystical_forest_ai.webp",
    "prompt": "Realistic person surrounded by glowing plants and soft fireflies, fog rays cutting through tall trees, green and gold lighting balance, magical realism tone, natural but fantastical.",
    "tags": ["portrait", "forest", "magical", "cinematic", "realistic", "ethereal"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 52,
    "dislikes": 1
  },
  {
    "id": 25,
    "name": "Noir City Portrait",
    "short": "Black-and-white city portrait with dramatic lighting",
    "description": "Real person in a black-and-white city portrait, dramatic lighting from side, light rain with reflections on asphalt, cinematic noir tone, ultra-detailed textures, emotional storytelling through posture and gaze.",
    "original": "assets/img/noir_city_original.webp",
    "ai": "assets/img/noir_city_ai.webp",
    "prompt": "Real person in a black-and-white city portrait, dramatic lighting from side, light rain with reflections on asphalt, cinematic noir tone, ultra-detailed textures, emotional storytelling through posture and gaze.",
    "tags": ["portrait", "noir", "city", "black-and-white", "cinematic", "realistic"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 108,
    "dislikes": 4
  },
  {
    "id": 26,
    "name": "Steampunk Inventor Portrait",
    "short": "Person with mechanical gadgets in Victorian lab",
    "description": "Transform the person into a steampunk inventor wearing Victorian clothing. Surround them with mechanical gadgets, brass instruments, gears, and steam in a cluttered workshop. Keep the face fully recognizable. Ultra-realistic, cinematic lighting, warm tones, detailed textures, and immersive environment.",
    "original": "assets/img/steampunk_inventor_original.webp",
    "ai": "assets/img/steampunk_inventor_ai.webp",
    "prompt": "Transform the person into a steampunk inventor wearing Victorian clothing. Surround them with mechanical gadgets, brass instruments, gears, and steam in a cluttered workshop. Keep the face fully recognizable. Ultra-realistic, cinematic lighting, warm tones, detailed textures, and immersive environment.",
    "tags": ["portrait", "steampunk", "cinematic", "Victorian", "realistic", "inventor"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 234,
    "dislikes": 11
  },
  {
    "id": 27,
    "name": "Tropical Island Explorer",
    "short": "Person on a lush beach with crystal-clear water",
    "description": "Transform the person into a tropical island explorer wearing casual adventure clothes. Place them on a lush beach with palm trees, crystal-clear water, and vibrant sunlight. Keep facial features realistic. Ultra-realistic textures, cinematic lighting, and vibrant, joyful atmosphere.",
    "original": "assets/img/tropical_island_original.webp",
    "ai": "assets/img/tropical_island_ai.webp",
    "prompt": "Transform the person into a tropical island explorer wearing casual adventure clothes. Place them on a lush beach with palm trees, crystal-clear water, and vibrant sunlight. Keep facial features realistic. Ultra-realistic textures, cinematic lighting, and vibrant, joyful atmosphere.",
    "tags": ["portrait", "island", "explorer", "realistic", "beach", "cinematic", "vibrant"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 76,
    "dislikes": 2
  },
  {
    "id": 28,
    "name": "Galactic Explorer",
    "short": "Person in futuristic astronaut suit with galaxy backdrop",
    "description": "Transform the person into a galactic explorer wearing a futuristic astronaut suit. Place them against a glowing galaxy backdrop with stars, planets, and nebulae. Keep the face recognizable inside the helmet. Ultra-realistic textures, cinematic lighting, and sci-fi details with cosmic reflections.",
    "original": "assets/img/galactic_explorer_original.webp",
    "ai": "assets/img/galactic_explorer_ai.webp",
    "prompt": "Transform the person into a galactic explorer wearing a futuristic astronaut suit. Place them against a glowing galaxy backdrop with stars, planets, and nebulae. Keep the face recognizable inside the helmet. Ultra-realistic textures, cinematic lighting, and sci-fi details with cosmic reflections.",
    "tags": ["portrait", "astronaut", "galaxy", "futuristic", "cinematic", "realistic", "space"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 159,
    "dislikes": 7
  },
  {
    "id": 29,
    "name": "Victorian Gentleman Portrait",
    "short": "Person in opulent room wearing Victorian attire",
    "description": "Transform the person into a Victorian gentleman wearing a tailored waistcoat, cravat, and pocket watch. Place them in an opulent room with ornate furniture, soft shadows, and warm lighting. Keep the face fully recognizable with ultra-realistic textures, cinematic composition, and elegant historical styling.",
    "original": "assets/img/victorian_gentleman_original.webp",
    "ai": "assets/img/victorian_gentleman_ai.webp",
    "prompt": "Transform the person into a Victorian gentleman wearing a tailored waistcoat, cravat, and pocket watch. Place them in an opulent room with ornate furniture, soft shadows, and warm lighting. Keep the face fully recognizable with ultra-realistic textures, cinematic composition, and elegant historical styling.",
    "tags": ["portrait", "Victorian", "cinematic", "realistic", "historical", "luxury"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 43,
    "dislikes": 1
  },
  {
    "id": 30,
    "name": "Floating Dreamscape Portrait",
    "short": "Person floating above mystical dreamscape with celestial lights",
    "description": "A surreal, cinematic portrait of the person floating above a mystical dreamscape. Celestial lights, soft clouds, and glowing particles surround the subject. Their face remains realistic and recognizable, while the environment is transformed into a magical, otherworldly scene with vibrant colors and depth.",
    "original": "assets/img/floating_dreamscape_original.webp",
    "ai": "assets/img/floating_dreamscape_ai.webp",
    "prompt": "A surreal, cinematic portrait of the person floating above a mystical dreamscape. Celestial lights, soft clouds, and glowing particles surround the subject. Their face remains realistic and recognizable, while the environment is transformed into a magical, otherworldly scene with vibrant colors and depth.",
    "tags": ["portrait", "dreamscape", "magical", "cinematic", "realistic", "floating"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 187,
    "dislikes": 8
  },
  {
    "id": 31,
    "name": "Futuristic Pilot Portrait",
    "short": "Person in high-tech flight suit with holographic HUD",
    "description": "Transform the person into a futuristic pilot wearing a high-tech flight suit. Add a holographic HUD interface floating around, neon cockpit reflections on the helmet visor, and glowing digital controls. Keep the face fully recognizable inside the visor, with cinematic, ultra-realistic lighting, 8K quality, sci-fi aesthetic, detailed textures, and immersive atmosphere.",
    "original": "assets/img/futuristic_pilot_original.webp",
    "ai": "assets/img/futuristic_pilot_ai.webp",
    "prompt": "Transform the person into a futuristic pilot wearing a high-tech flight suit. Add a holographic HUD interface floating around, neon cockpit reflections on the helmet visor, and glowing digital controls. Keep the face fully recognizable inside the visor, with cinematic, ultra-realistic lighting, 8K quality, sci-fi aesthetic, detailed textures, and immersive atmosphere.",
    "tags": ["portrait", "pilot", "futuristic", "cinematic", "sci-fi", "realistic", "HUD"],
    "model": "Gemini",
    "resolution": "3840x2160",
    "likes": 95,
    "dislikes": 3
  },
  {
    "id": 32,
    "name": "Neon Music Producer",
    "short": "Person in neon-lit studio with holographic instruments",
    "description": "Visualize the person as a futuristic music producer in a neon-lit studio. Surrounded by holographic synthesizers, floating sound waves, and glowing audio controls. Keep the person’s face recognizable. Mood is cinematic, vibrant, and energetic, with ultra-realistic lighting and reflections. Include subtle lens flares and detailed environment textures.",
    "original": "assets/img/neon_music_producer_original.webp",
    "ai": "assets/img/neon_music_producer_ai.webp",
    "prompt": "Visualize the person as a futuristic music producer in a neon-lit studio. Surrounded by holographic synthesizers, floating sound waves, and glowing audio controls. Keep the person’s face recognizable. Mood is cinematic, vibrant, and energetic, with ultra-realistic lighting and reflections. Include subtle lens flares and detailed environment textures.",
    "tags": ["portrait", "music", "studio", "cinematic", "neon", "realistic", "producer"],
    "model": "ChatGPT",
    "resolution": "3840x2160",
    "likes": 128,
    "dislikes": 5
  },
  {
    "id": 33,
    "name": "Futuristic Tech Executive",
    "short": "Person in futuristic corporate office with holographic workstation",
    "description": "Transform the person into a cutting-edge tech executive in a futuristic corporate office. Wearing a sleek suit with subtle neon accents, seated at a holographic workstation with floating digital graphs and charts. Face remains fully realistic. Background features a panoramic city skyline with soft futuristic lighting. Ultra-detailed textures, cinematic realism, and professional, visionary atmosphere.",
    "original": "assets/img/futuristic_exec_original.webp",
    "ai": "assets/img/futuristic_exec_ai.webp",
    "prompt": "Transform the person into a cutting-edge tech executive in a futuristic corporate office. Wearing a sleek suit with subtle neon accents, seated at a holographic workstation with floating digital graphs and charts. Face remains fully realistic. Background features a panoramic city skyline with soft futuristic lighting. Ultra-detailed textures, cinematic realism, and professional, visionary atmosphere.",
    "tags": ["portrait", "executive", "futuristic", "cinematic", "realistic", "corporate"],
    "model": "Microsoft Copilot",
    "resolution": "3840x2160",
    "likes": 64,
    "dislikes": 2
  },
  {
    "id": 34,
    "name": "Fantasy Hero Portrait",
    "short": "Person as heroic figure in fantasy world",
    "description": "Transform the person into a heroic figure in a fantasy world. Wearing intricate armor, holding a glowing sword or staff, standing on a cliff with storm clouds and magical light around. Keep the face fully realistic and expressive. Cinematic composition with dynamic lighting, realistic textures, and dramatic environmental storytelling.",
    "original": "assets/img/fantasy_hero_original.webp",
    "ai": "assets/img/fantasy_hero_ai.webp",
    "prompt": "Transform the person into a heroic figure in a fantasy world. Wearing intricate armor, holding a glowing sword or staff, standing on a cliff with storm clouds and magical light around. Keep the face fully realistic and expressive. Cinematic composition with dynamic lighting, realistic textures, and dramatic environmental storytelling.",
    "tags": ["portrait", "fantasy", "hero", "cinematic", "realistic", "armor", "magical"],
    "model": "ChatGPT",
    "resolution": "3840x2160",
    "likes": 213,
    "dislikes": 10
  },
  {
    "id": 35,
    "name": "Time-Travel Adventurer",
    "short": "Person as time-travel explorer with collapsed city",
    "description": "Visualize the person as a time-travel adventurer, with futuristic gadgets, vintage compass, and a rugged outfit blending past and future styles. Background shows a partially collapsed ancient city with glowing temporal portals. Maintain full facial realism. Ultra-detailed textures, cinematic light, and dynamic depth for storytelling.",
    "original": "assets/img/time_travel_adventurer_original.webp",
    "ai": "assets/img/time_travel_adventurer_ai.webp",
    "prompt": "Visualize the person as a time-travel adventurer, with futuristic gadgets, vintage compass, and a rugged outfit blending past and future styles. Background shows a partially collapsed ancient city with glowing temporal portals. Maintain full facial realism. Ultra-detailed textures, cinematic light, and dynamic depth for storytelling.",
    "tags": ["portrait", "time-travel", "adventurer", "cinematic", "realistic", "fantasy"],
    "model": "ChatGPT",
    "resolution": "3840x2160",
    "likes": 142,
    "dislikes": 6
  }

/*
  {
    id: 1000001,
    name: "Cinematic Landscape",
    short: "Epic fantasy mountain scene",
    description: "A dramatic cinematic landscape featuring towering mountains bathed in golden hour lighting. This prompt creates stunning wide-angle shots perfect for fantasy or adventure themes.",
    original: "assets/img/1.png",
    ai: "assets/img/2.png",
    prompt: "Epic cinematic landscape, golden hour lighting, ultra detailed, 8k, --ar 16:9 --v 5",
    tags: ["landscape", "cinematic", "fantasy", "golden hour"],
    model: "Stable Diffusion XL",
    resolution: "1024x576",
    likes: 42,
    dislikes: 3
  },
  {
    id: 10000002,
    name: "Anime Character",
    short: "Stylized anime girl portrait",
    description: "High-quality anime-style portrait with soft pastel colors and detailed facial features. Perfect for character design and illustration work.",
    original: "assets/vid/1.m4",
    ai: "assets/vid/.mp4",
    prompt: "Anime girl portrait, soft pastel colors, detailed eyes, trending on pixiv",
    tags: ["anime", "portrait", "character", "pastel"],
    model: "NovelAI",
    resolution: "512x768",
    likes: 28,
    dislikes: 5
  },
  {
    id: 100003,
    name: "Cyberpunk City",
    short: "Futuristic neon cityscape",
    description: "A vibrant cyberpunk cityscape with neon lights, flying cars, and towering skyscrapers. Perfect for sci-fi and futuristic themes.",
    original: "assets/vid/1mp4",
    ai: "assets/vid/24",
    prompt: "Cyberpunk cityscape, neon lights, flying cars, rain, night scene, ultra detailed",
    tags: ["cyberpunk", "city", "neon", "futuristic"],
    model: "Midjourney",
    resolution: "1024x1024",
    likes: 35,
    dislikes: 2
  }*/
];
